name: Go

on:
  push:
    branches: [ "master", "develop", "feature/**", "bugfix/**", "hotfix/**", "merge/**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: fmt
        run: |
          GOFMT_FILES?=$$(find . -name '*.go' | grep -v vendor)
          gofmt -w $(GOFMT_FILES)
      - name: lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
          golangci-lint run -v -c .golangci.yml ./...
      - name: test
        run: go test ./... -timeout=2m -parallel=4